# Generated by Django 4.2.4 on 2023-09-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('empid', models.CharField(max_length=20, unique=True)),
                ('designation', models.CharField(max_length=50)),
                ('date_of_joining', models.DateField()),
                ('department', models.CharField(max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('experience', models.PositiveIntegerField()),
            ],
        ),
    ]
